server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8


spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

logging.file: "logs/chatroom.log"
logging:
  file:
    max-size: 10MB
    max-history: 20
  level:
    root: INFO
    org.springframework: ERROR
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan}[lineNo:%line]    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineNo:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

